# -*- coding: utf-8 -*-
"""
Created on 2021-09-19 17:32:59
---------
@summary:
---------
@author: cxhuan
"""

from feapder import Item


class ReportItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i report 1.
    """

    __table_name__ = "report"

    def __init__(self, *args, **kwargs):
        self.count = kwargs.get('count')
        self.emRatingName = kwargs.get('emRatingName')  # 评级名称
        self.emRatingValue = kwargs.get('emRatingValue')  # 评级代码
        self.encodeUrl = kwargs.get('encodeUrl')  # 链接
        # self.id = kwargs.get('id')
        self.indvInduCode = kwargs.get('indvInduCode')  # 行业代码
        self.indvInduName = kwargs.get('indvInduName')  # 行业名称
        self.lastEmRatingName = kwargs.get('lastEmRatingName')  # 上次评级名称
        self.lastEmRatingValue = kwargs.get('lastEmRatingValue')  # 上次评级代码
        self.orgCode = kwargs.get('orgCode')  # 机构代码
        self.orgName = kwargs.get('orgName')  # 机构名称
        self.orgSName = kwargs.get('orgSName')  # 机构简称
        self.predictNextTwoYearEps = kwargs.get('predictNextTwoYearEps')
        self.predictNextTwoYearPe = kwargs.get('predictNextTwoYearPe')
        self.predictNextYearEps = kwargs.get('predictNextYearEps')
        self.predictNextYearPe = kwargs.get('predictNextYearPe')
        self.predictThisYearEps = kwargs.get('predictThisYearEps')
        self.predictThisYearPe = kwargs.get('predictThisYearPe')
        self.publishDate = kwargs.get('publishDate')  # 发表时间
        self.ratingChange = kwargs.get('ratingChange')  # 评级变动
        self.researcher = kwargs.get('researcher')  # 研究员
        self.stockCode = kwargs.get('stockCode')  # 股票代码
        self.stockName = kwargs.get('stockName')  # 股票简称
        self.title = kwargs.get('title')  # 报告名称
